config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'dashboard', to: 'users#show', as: 'user'
  resources :tents do
    resources :reviews, only: [ :create ]
  end
  root to: 'tents#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :tent
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :tent
  belongs_to :user
  validates :content, length: { minimum: 2, maximum: 150 }
end

app/models/tent.rb
class Tent < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy

  validates :title, presence: true
  validates :title, uniqueness: true
  validates :capacity, presence: true
  validates :title, length: { minimum: 4, maximum: 255 }
  validates :description, presence: true
  validates :location, presence: true
  validates :price, presence: true
  validates :price, numericality: { only_integer: true }
  validates :wildlife, presence: true
  validates :photo, presence: true

  mount_uploader :photo, PhotoUploader

  def self.wildlife_options
    ["Bear", "Cactus", "Deer", "Fish", "Moose", "Raccoon", "Spider", "Squirrel", "Turkey", "Horse"]
  end

  include PgSearch
  pg_search_scope :search_tents,
    against: [:title, :description, :location, :wildlife],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :tents
  has_many :bookings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Verify User; before action and then skip as needed (Index/Show/New)
  before_action :authenticate_user!

  # Add Permissions to AppController
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def after_sign_in_path_for(resource)
    root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @tent = Tent.find(params[:tent_id])
    @review.tent = @tent
    @review.user = current_user
    if @review.save
      redirect_to tent_path(@tent), notice: "Thanks for your review!"
    else
      raise
      render 'tents/show'
    end
  end

  private
  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/tent_controller.rb
class TentController < ApplicationController
  # Verify User; before action and then skip as needed (Index/Show/New)
  skip_before_action :authenticate_user!, only: [:show, :index, :new]

  def index
    @tents = Tent.all
  end

  def show
    @tent = Tent.find(params[:id])
  end

  def new
    @tent = Tent.new
  end

  def create
    @tent = Tent.new(tent_params)
    if @tent.saves
      redirect_to tent_path(@tent)
    else
      render :new
    end
  end

  def destroy
  end

  def update
    # @tent = Tent.find(params[:id])
    # create
  end

  def edit
  end

  private
  # Validation to allow name and nothing else into the form
  def tent_params
    params.require(:tent).permit(:title, :capacity, :description, :location, :price, :wildlife, :photo, :create)
  end
end

app/controllers/tents_controller.rb
class TentsController < ApplicationController
  # Verify User; before action and then skip as needed (Index/Show/New)
  skip_before_action :authenticate_user!, only: [:show, :index, :new]

  def index
    if params[:query]
      @tents = Tent.search_tents(params[:query])
    else
      @tents = Tent.all
    end
  end

  def show
    @tent = Tent.find(params[:id])
    @review = Review.new
  end

  def new
    @tent = Tent.new
  end

  def create
    wildlife = params.require(:tent)["wildlife"][1..-1].join(", ")
    @tent = Tent.new(tent_params)
    @tent.wildlife = wildlife
    @tent.user = current_user
    if @tent.save
      redirect_to tent_path(@tent)
    else
      puts @tent
      render :new
    end
  end

  def destroy
  end

  def update
    # @tent = Tent.find(params[:id])
    # create
  end

  def edit
  end

  private

  # Validation to allow name and nothing else into the form
  def tent_params
    params.require(:tent).permit(:title, :capacity, :description, :location, :price, :wildlife, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Rent a Tent</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %>
    <script src="https://kit.fontawesome.com/36197ad289.js"></script>
    <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>

<body>

    <div id="page-container">



        <!-- Here will be the specific page content -->
        <%= yield %>

        <p class="notice mb-0">
            <%= notice %>
        </p>
        <p class="alert">
            <%= alert %>
        </p>

        <%= javascript_include_tag 'application' %>
        <%= javascript_pack_tag 'application' %>
    </div>
</body>

</html>

app/views/pages/home.html.erb
<%= render 'components/default_header' %>
<div id="content-wrapper">
    <div id="content-container">
        <h1>Pages#home</h1>
        <p>Find me in app/views/pages/home.html.erb</p>
    </div>
</div>

app/views/review/create.html.erb
<h1>Review#create</h1>
<p>Find me in app/views/review/create.html.erb</p>

app/views/tents/create.html.erb
<h1>Tent#create</h1>
<p>Find me in app/views/tent/create.html.erb</p>

app/views/tents/destroy.html.erb
<h1>Tent#destroy</h1>
<p>Find me in app/views/tent/destroy.html.erb</p>

app/views/tents/edit.html.erb
<%= render 'components/search_bar' %>
<div id="content-wrapper">
    <div class="content-shadow">
        <div id="content-container">
            <h1>Tent#edit</h1>
            <p>Find me in app/views/tent/edit.html.erb</p>
        </div>
    </div>
</div>

app/views/tents/index.html.erb
<%= render 'components/default_header' %>
<div id="content-wrapper" class="header-present background-intelligent-cover is-blurred is-fixed-to-viewport"
    data-background-image="<%= image_path 'background_autumn.jpg' %>">
    <div class="content-shadow">
        <div id="content-container">
            <div class="grid-content py-4 mb-4">
                <div>
                    <h3>Book a Tent – Escape Now.</h3>
                    <br>
                    <p>Utilize <strong>Pitch-a-Tent</strong> to blow off some steam, escaping city-life stress. Our
                        service provides a plethora of options, ensuring everyone can find an experience they enjoy!</p>

                </div>
                <div class="icon-list">
                    <ul>
                        <li><i class="fas fa-leaf"></i>Pure Wildness</li>
                        <li><i class="fas fa-temperature-low"></i>Every Weather</li>
                        <li><i class="fab fa-tencent-weibo"></i>Sustainable</li>
                        <li><i class="fab fa-gripfire"></i>Wild fires</li>
                    </ul>
                </div>
                <div class="action-list">
                    <ul>
                        <li>
                            <p>Have a free tent? Want to make some money? Rent out your own tent to the community!</p>
                        </li>
                        <li>
                            <%= link_to 'Add your own tent', new_tent_path, class:"btn btn-primary"%>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="icon_hr">
                <i class="fas fa-paw"></i>
                <i class="fas fa-feather"></i>
                <i class="fas fa-crow"></i>
            </div>

            <div class="cards mt-4">
                <% @tents.each do |tent| %>
                <%= render partial: 'components/tent_card', locals: { tent: tent } %>
                <% end %>
            </div>
        </div>
    </div>
</div>
<%= render 'components/footer' %>

app/views/tents/new.html.erb
<%= render 'components/search_bar' %>
<div id="content-wrapper" class="background-intelligent-cover is-blurred is-fixed-to-viewport"
    data-background-image="<%= image_path('background_lake_tent_edited.jpg') %>">
    <div class="content-shadow">
        <!--    <div class="content-create-tent">-->
        <div id="content-container">
            <div class="login">
                <div class="login-form">
                    <h1>Rent your Tent!</h1>
                    <%= simple_form_for @tent do |f| %>
                    <%= f.input :title %>
                    <%= f.input :capacity %>
                    <%= f.input :description %>
                    <%= f.input :location %>
                    <%= f.input :price %>
                    <%= f.input :wildlife, collection: Tent.wildlife_options, input_html: { multiple: true } %>
                    <%= f.input :photo %>
                    <%= f.input :photo_cache, as: :hidden %>
                    <%= f.button :submit %>
                    <% end %>
                </div>
            </div>
            <!--    </div>-->
        </div>
    </div>
</div>
<%= render partial:'/components/footer', locals: { is_above: true } %>

app/views/tents/show.html.erb
<%= render 'components/search_bar' %>
<div id="content-wrapper" class="background-intelligent-cover is-blurred is-fixed-to-viewport"
    data-background-image="<%= image_path('background_leaves.jpg') %>">
    <!-- <div id="content-wrapper" class="background-intelligent-cover is-fixed-to-viewport" data-background-image="<%= cl_image_path(@tent.photo) %>"> -->
    <div class="content-shadow">
        <div id="content-container">
            <!--             <img src="" alt="" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path(@tent.photo);%>);"> -->
            <%#= cl_image_tag(@tent.photo) %>
            <div class="background-container">
                <div>
                    <div class="grid-container">
                        <div class="photo-show">
                            <!-- <div> -->
                            <%= cl_image_tag(@tent.photo, width: 380, height:250, crop: :fill) %>
                            <!-- </div> -->
                            <!-- <div>
                                <div>
                                    <p>Small Photo</p>
                                    <p>Small Photo</p>
                                </div>
                                <div>
                                    <p>Small Photo</p>
                                    <p>Small Photo</p>
                                </div>
                            </div> -->
                        </div>
                        <div class="content-show content-box">
                            <div class="content-upper-show">
                                <div id="title-cost-show">
                                    <h1>
                                        <%= @tent.title %>
                                    </h1>
                                    <h5>€
                                        <%= @tent.price %>
                                    </h3>
                                </div>
                                <div>
                                    <p>
                                        <%= @tent.description %>
                                    </p>
                                </div>
                            </div>
                            <div class="content-mid-show">
                                <div class="w3-row">
                                    <a href="javascript:void(0)" onclick="openCity(event, 'London');">
                                        <div class="w3-third tablink w3-bottombar w3-hover-light-grey w3-padding w3-border-blue">Details</div>
                                    </a>
                                    <a href="javascript:void(0)" onclick="openCity(event, 'Paris');">
                                        <div class="w3-third tablink w3-bottombar w3-hover-light-grey w3-padding">Wildlife</div>
                                    </a>
                                    <a href="javascript:void(0)" onclick="openCity(event, 'Tokyo');">
                                        <div class="w3-third tablink w3-bottombar w3-hover-light-grey w3-padding">Review</div>
                                    </a>
                                </div>
                                <div id="London" class="w3-container city" style="display:block">
                                    <h5>Host:
                                        <%= @tent.user.name %>
                                    </h5>
                                    <h5>Capacity:
                                        <%= @tent.capacity %>
                                    </h5>
                                    <h5>Location:
                                        <%= @tent.location %>
                                    </h5>
                                    <h5>Landscape: Forest
                                    </h5>
                                </div>
                                <div id="Paris" class="w3-container city" style="display:none">
                                    <p>
                                        <% animal_array = @tent.wildlife.split(",") %>
                                        <% animal_array.each do |animal| %>
                                        <ul>
                                            <li>
                                                <%= animal %>
                                            </li>
                                        </ul>
                                        <% end %>
                                    </p>
                                </div>
                                <div id="Tokyo" class="w3-container city" style="display:none">
                                    <div id="reviews">
                                    </div>
                                    <%= simple_form_for([ @tent, @review ]) do |form| %>
                                    <br>
                                    <%= form.input :content, as: :text, label: false, placeholder: "Write your review here for #{@tent.title}"  %>
                                    <%= form.button :submit, class:"btn btn-primary"%>

                                    <% end %>
                                </div>
                                <script>
                                    function openCity(evt, cityName) {
                                    var i, x, tablinks;
                                    x = document.getElementsByClassName("city");
                                    for (i = 0; i < x.length; i++) {
                                        x[i].style.display = "none";
                                    }
                                    tablinks = document.getElementsByClassName("tablink");
                                    for (i = 0; i < x.length; i++) {
                                        tablinks[i].className = tablinks[i].className.replace(" w3-border-blue", "");
                                    }
                                    document.getElementById(cityName).style.display = "block";
                                    evt.currentTarget.firstElementChild.className += " w3-border-blue";
                                }
                                </script>
                            </div>
                            <div class="content-low-show">
                                <div class="book-show">
                                    <form class="form-book">
                                        <input type="text" name="start date" value="Start Date">
                                        <input type="text" name="end date" value="End Date">
                                    </form>
                                    <%= link_to 'Book Now!', new_tent_path, class:"btn btn-primary"%>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="review-container content-box mt-4">
                        <div>
                          <br>
                          <br>
                            <h2>
                                <%= pluralize @tent.reviews.size, "Reviews" %>
                            </h2>
                        </div>
                        <div class="border-underline">
                          <br>
                          <% if @tent.reviews.blank? %>
                          Be the first to leave a review for
                          <%= @tent.title %>
                          <% else %>
                          <% @tent.reviews.each do |review| %>
                          <p>
                              <%= review.content %>
                          </p>
                          <% end %>
                          <% end %>
                        </div>
                    </div>
                </div>
            </div>
            <%#= render 'reviews/form', tent: @tent, review: @review %>
        </div>
    </div>
</div>
<%= render 'components/footer' %>
</div>

app/views/tents/update.html.erb
<h1>Tent#update</h1>
<p>Find me in app/views/tent/update.html.erb</p>

app/views/users/show.html.erb
<%= render 'components/search_bar' %>
<div id="content-wrapper" class="background-intelligent-cover is-blurred is-fixed-to-viewport" data-background-image="<%= image_path 'background_autumn.jpg' %>">
    <div class="content-shadow">
        <div id="content-container">
            <div>
              <div class="user-card">

                <div class="card-product">
                    <img src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png" />
                    <div class="card-product-infos">
                        <h3>Good afternoon
                            <strong><%= current_user.name %></strong>
                        </h3>
                        <p>User since: <%= current_user.created_at.strftime("%F") %></p>
                        <hr>
                        <p><%= current_user.description %></p>
                    </div>
                </div>


                <h2 style="color: white; padding-top: 30px;">Your Listings</h2>
                <hr>
                     <div class="cards mt-4">
              <% @current_id = current_user.id %>
                <% current_user.tents.each do |tent| %>
                <%= render partial: 'components/tent_card', locals: { tent: tent } %>
                <% end %>
            </div>

              </div>





            </div>
        </div>
    </div>
</div>
<%= render partial:'/components/footer', locals: { is_above: true } %>